name: saudi_adaminnovations
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+114

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  awesome_dialog: 
  badges:
  cached_network_image: 
  carousel_slider: 
  connectivity_plus:
  country_pickers:
  cupertino_icons: 
  dio:
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_countdown_timer: 
  flutter_facebook_auth: 
  flutter_holo_date_picker: 
  flutter_inappwebview: 
  flutter_isolate: 
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar:
  flutter_screenutil:
  flutter_slidable:
  flutter_spinkit:
  flutter_staggered_grid_view:
  flutter_svg:
  flutter_switch:
  flutter_widget_from_html:
  fluttertoast:
  get:
  get_storage:
  google_sign_in:
  hive:
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^1.0.4
  intl:
  lottie: 
  material_design_icons_flutter: ^7.0.7296
  modal_bottom_sheet: ^2.1.0
  money_formatter: ^0.0.3
  onesignal_flutter:
  open_file_plus: ^3.3.0

  pagination_view: ^2.0.0
  path: ^1.7.0
  path_provider: ^2.1.1
  pin_code_fields: ^8.0.1
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  ribbon_widget: ^1.0.5
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer:
  timelines: ^0.1.0
  url_launcher:
  photo_view: ^0.14.0
  chewie: ^1.3.5
  rive: ^0.9.1
  youtube_player_flutter:

  country_code_picker: ^3.0.0

dev_dependencies:



  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/details/
    - assets/icons/track_order/
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins LightItalic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
